[platformio]
default_envs = m5stack-stamps3

[env:m5stack-stamps3]
platform = https://github.com/pioarduino/platform-espressif32.git#54.03.21
board = m5stack-stamps3
framework = arduino
monitor_speed = 115200
upload_speed = 1500000
build_flags =
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
extra_scripts =
  pre:tools/esptool_compat.py
  post:tools/esptool_compat.py
platform_packages =
  tool-esptoolpy @ platformio/tool-esptoolpy@1.40801.0
lib_deps =
  m5stack/M5Cardputer
  m5stack/M5Unit-ENV
  z3t0/IRremote@^4.7.1
  knolleary/PubSubClient@^2.8
  bblanchon/ArduinoJson@^6.21.5
  olikraus/U8g2@^2.36.12
  jgromes/RadioLib
  https://github.com/m5stack/TinyGPSPlus.git
