[platformio]
default_envs = xiao_esp32s3

[env:xiao_esp32s3]
platform = https://github.com/pioarduino/platform-espressif32.git#54.03.21
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_flags =
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
extra_scripts =
  pre:../../tools/esptool_compat.py
  post:../../tools/esptool_compat.py
platform_packages =
  tool-esptoolpy @ platformio/tool-esptoolpy@1.40801.0
lib_deps =
  jgromes/RadioLib
