#include "app.h"

const MenuItem MENU_ITEMS[] = {
    {"Battery", Screen::BatteryInfo},
    {"System", Screen::SystemInfo},
    {"WiFi Scan", Screen::WifiScan},
    {"Saved WiFi", Screen::SavedWifi},
    {"WiFi Connect", Screen::WifiConnect},
    {"Pi Monitor", Screen::PiMonitor},
    {"Voice Memos", Screen::VoiceMemos},
    {"Environment", Screen::Environment},
    {"OLED Test", Screen::OledTest},
    {"GNSS Dash", Screen::GnssDashboard},
    {"GNSS Sky", Screen::GnssSkyView},
    {"LoRa Diag", Screen::LoraDiag},
    {"Level", Screen::LevelTool},
};
const int MENU_ITEM_COUNT = sizeof(MENU_ITEMS) / sizeof(MENU_ITEMS[0]);

SHT3X envSht30;
QMP6988 envQmp6988;
U8G2_SSD1309_128X64_NONAME0_F_HW_I2C oledDisplay(U8G2_R0, U8X8_PIN_NONE);
WiFiClient piMonitorWifiClient;
PubSubClient piMonitorMqttClient(piMonitorWifiClient);
Screen currentScreen = Screen::MainMenu;
int selectedMenuIndex = 0;
int menuScrollOffset = 0;
unsigned long lastSystemRefreshMs = 0;
unsigned long lastLevelRefreshMs = 0;
unsigned long lastOledRefreshMs = 0;
unsigned long lastOledInitAttemptMs = 0;
unsigned long lastBatterySampleMs = 0;
unsigned long lastEnvironmentRefreshMs = 0;
unsigned long lastEnvironmentRetryMs = 0;
unsigned long lastLoraDiagServiceMs = 0;
unsigned long lastLoraDiagRenderMs = 0;
unsigned long lastGnssDashboardServiceMs = 0;
unsigned long lastGnssDashboardRenderMs = 0;
unsigned long lastGnssSkyViewServiceMs = 0;
unsigned long lastGnssSkyViewRenderMs = 0;
unsigned long lastGnssSkyGsvMs = 0;
M5Canvas contentCanvas(&M5Cardputer.Display);
bool contentCanvasReady = false;
BatteryTrend batteryTrend;
WifiNetwork wifiNetworks[MAX_WIFI_NETWORKS];
int wifiNetworkCount = 0;
int selectedWifiIndex = 0;
int wifiScrollOffset = 0;
Preferences wifiPrefs;
String savedWifiNames[MAX_SAVED_WIFI_NAMES];
int savedWifiCount = 0;
int selectedSavedWifiIndex = 0;
int savedWifiScrollOffset = 0;
String wifiSaveMessage;
String wifiSaveResultSsid;
String pendingDeleteWifiName;
int pendingDeleteWifiIndex = -1;
String savedWifiDeleteResultName;
String savedWifiDeleteResultMessage;
String wifiConnectStatus = "Not connected.";
String wifiConnectSsid;
String wifiConnectIp;
String piMonitorStatus = "Not connected.";
String piMonitorBrokerHost;
uint16_t piMonitorBrokerPort = PI_MQTT_DEFAULT_PORT;
String piMonitorDeviceId = PI_MONITOR_DEFAULT_DEVICE_ID;
String piMonitorCommandTarget;
String piMonitorSelectedCommandTarget;
String piMonitorCommandStatus = "No command sent.";
uint32_t piMonitorCommandCount = 0;
int piMonitorSetIntervalIndex = 1;
uint32_t piMonitorSetIntervalCommandCount = 0;
String piMonitorLastResponseDevice;
String piMonitorLastResponseSummary;
uint32_t piMonitorResponseCount = 0;
unsigned long piMonitorLastCommandSentMs = 0;
uint32_t piMonitorStatusPublishCount = 0;
unsigned long piMonitorLastStatusPublishMs = 0;
bool piMonitorConfigLoaded = false;
String piMonitorLastTopic;
String piMonitorLastPayload;
uint32_t piMonitorMessageCount = 0;
PiMonitorDevice piMonitorDevices[MAX_PI_MONITOR_DEVICES];
VoiceMemoFile voiceMemos[MAX_VOICE_MEMOS];
int voiceMemoCount = 0;
int selectedVoiceMemoIndex = 0;
int voiceMemoScrollOffset = 0;
bool voiceSdInitialized = false;
bool voiceSdAvailable = false;
bool voiceMemoRecording = false;
bool voiceMemoPlaying = false;
bool envSensorInitialized = false;
bool envSht30Ready = false;
bool envQmp6988Ready = false;
bool envHasTempHumidity = false;
bool envHasPressure = false;
bool envPressureInvalid = false;
bool i2cHubDetected = false;
bool oledInitialized = false;
bool oledOnline = false;
bool loraDiagInitialized = false;
bool loraIoExpanderDetected = false;
bool loraRfSwitchEnabled = false;
bool loraRadioReady = false;
bool loraListening = false;
bool loraGnssStarted = false;
bool loraGnssLocationValid = false;
bool loraGnssSatellitesValid = false;
bool loraGnssHdopValid = false;
bool loraGnssTimeValid = false;
bool loraGnssDateValid = false;
bool loraGnssSpeedValid = false;
bool loraGnssAltitudeValid = false;
bool gnssDashboardInitialized = false;
bool gnssSkyViewInitialized = false;
bool envLogging = false;
File voiceMemoFile;
File envLogFile;
String voiceMemoStatus;
String activeVoiceMemoName;
String activeVoiceMemoPath;
String pendingVoiceMemoDeleteName;
String pendingVoiceMemoDeletePath;
String voiceMemoDeleteResultMessage;
String envStatus = "Not initialized.";
String i2cHubStatus = "Direct Grove";
String oledStatus = "Not initialized.";
String oledStatusLine;
String loraStatus = "Not initialized.";
String loraRadioStatus = "Not initialized.";
String loraGnssStatus = "Not started.";
String loraLastPacket;
String loraLastNmeaLine;
String envLogStatus;
String envLogFileName;
String envLogFilePath;
String envLogNameInput;
uint32_t voiceMemoRecordedBytes = 0;
uint32_t envLogSampleCount = 0;
uint32_t oledDrawCount = 0;
unsigned long voiceMemoRecordingStartedMs = 0;
unsigned long lastVoiceMemoRenderMs = 0;
int16_t voiceRecordBuffer[VOICE_RECORD_CHUNK_SAMPLES];
int lastBatteryVoltageMv = 0;
int lastBatteryLevel = -1;
int lastVbusVoltageMv = -1;
int lastBatteryCurrentMa = 0;
int i2cHubActiveChannel = -1;
int loraRadioState = 0;
int sharedSpiOwner = SHARED_SPI_OWNER_NONE;
uint8_t oledActiveAddress = 0;
m5::Power_Class::is_charging_t lastChargingStatus = m5::Power_Class::charge_unknown;
GnssSkySatellite gnssSkySatellites[GNSS_SKY_MAX_SATELLITES];
float envTemperatureC = 0.0f;
float envHumidityPercent = 0.0f;
float envPressureHpa = 0.0f;
float loraLastRssi = 0.0f;
float loraLastSnr = 0.0f;
double loraGnssLatitude = 0.0;
double loraGnssLongitude = 0.0;
float loraGnssHdop = 0.0f;
float loraGnssSpeedKmph = 0.0f;
float loraGnssAltitudeMeters = 0.0f;
uint32_t loraPacketCount = 0;
uint32_t loraCrcErrorCount = 0;
uint32_t loraReceiveErrorCount = 0;
uint32_t loraGnssByteCount = 0;
uint32_t loraGnssLineCount = 0;
uint32_t loraGnssCharsParsed = 0;
uint32_t loraGnssPassedChecksum = 0;
uint32_t loraGnssFailedChecksum = 0;
uint32_t loraGnssFixAgeMs = 0;
uint32_t loraGnssSatellites = 0;
uint32_t gnssSkySatelliteCount = 0;
uint32_t gnssSkySatellitesInView = 0;
uint32_t gnssSkyGsvSentenceCount = 0;
uint16_t loraGnssYear = 0;
uint8_t loraGnssMonth = 0;
uint8_t loraGnssDay = 0;
uint8_t loraGnssHour = 0;
uint8_t loraGnssMinute = 0;
uint8_t loraGnssSecond = 0;
float smoothedLevelX = 0.0f;
float smoothedLevelY = 0.0f;
bool levelSmoothingInitialized = false;
