#include "app.h"

const MenuItem MENU_ITEMS[] = {
    {"Battery", Screen::BatteryInfo},
    {"System", Screen::SystemInfo},
    {"WiFi Scan", Screen::WifiScan},
    {"Saved WiFi", Screen::SavedWifi},
    {"WiFi Connect", Screen::WifiConnect},
    {"Pi Monitor", Screen::PiMonitor},
    {"SD Manager", Screen::SdManager},
    {"Voice Memos", Screen::VoiceMemos},
    {"Environment", Screen::Environment},
    {"OLED Test", Screen::OledTest},
    {"RTC", Screen::RtcStatus},
    {"GNSS Dash", Screen::GnssDashboard},
    {"GNSS Sky", Screen::GnssSkyView},
    {"Return Home", Screen::ReturnHome},
    {"Breadcrumbs", Screen::BreadcrumbLogger},
    {"LoRa Packets", Screen::LoraPacketMonitor},
    {"LoRa Diag", Screen::LoraDiag},
    {"Level", Screen::LevelTool},
};
const int MENU_ITEM_COUNT = sizeof(MENU_ITEMS) / sizeof(MENU_ITEMS[0]);

SHT3X envSht30;
QMP6988 envQmp6988;
U8G2_SSD1309_128X64_NONAME0_F_HW_I2C oledDisplay(U8G2_R0, U8X8_PIN_NONE);
WiFiClient piMonitorWifiClient;
PubSubClient piMonitorMqttClient(piMonitorWifiClient);
Screen currentScreen = Screen::MainMenu;
int selectedMenuIndex = 0;
int menuScrollOffset = 0;
unsigned long lastSystemRefreshMs = 0;
unsigned long lastLevelRefreshMs = 0;
unsigned long lastOledRefreshMs = 0;
unsigned long lastOledInitAttemptMs = 0;
unsigned long lastRtcRefreshMs = 0;
unsigned long lastRtcRetryMs = 0;
unsigned long lastBatterySampleMs = 0;
unsigned long lastEnvironmentRefreshMs = 0;
unsigned long lastEnvironmentRetryMs = 0;
unsigned long lastLoraDiagServiceMs = 0;
unsigned long lastLoraDiagRenderMs = 0;
unsigned long lastGnssDashboardServiceMs = 0;
unsigned long lastGnssDashboardRenderMs = 0;
unsigned long lastGnssSkyViewServiceMs = 0;
unsigned long lastGnssSkyViewRenderMs = 0;
unsigned long lastGnssSkyGsvMs = 0;
unsigned long lastReturnHomeServiceMs = 0;
unsigned long lastReturnHomeRenderMs = 0;
unsigned long lastBreadcrumbLoggerServiceMs = 0;
unsigned long lastBreadcrumbLoggerRenderMs = 0;
unsigned long lastBreadcrumbLogSampleMs = 0;
unsigned long lastLoraPacketMonitorServiceMs = 0;
unsigned long lastLoraPacketMonitorRenderMs = 0;
unsigned long loraPacketMonitorLastPacketMs = 0;
M5Canvas contentCanvas(&M5Cardputer.Display);
bool contentCanvasReady = false;
BatteryTrend batteryTrend;
WifiNetwork wifiNetworks[MAX_WIFI_NETWORKS];
int wifiNetworkCount = 0;
int selectedWifiIndex = 0;
int wifiScrollOffset = 0;
Preferences wifiPrefs;
String savedWifiNames[MAX_SAVED_WIFI_NAMES];
int savedWifiCount = 0;
int selectedSavedWifiIndex = 0;
int savedWifiScrollOffset = 0;
String wifiSaveMessage;
String wifiSaveResultSsid;
String pendingDeleteWifiName;
int pendingDeleteWifiIndex = -1;
String savedWifiDeleteResultName;
String savedWifiDeleteResultMessage;
String wifiConnectStatus = "Not connected.";
String wifiConnectSsid;
String wifiConnectIp;
String piMonitorStatus = "Not connected.";
String piMonitorBrokerHost;
uint16_t piMonitorBrokerPort = PI_MQTT_DEFAULT_PORT;
String piMonitorDeviceId = PI_MONITOR_DEFAULT_DEVICE_ID;
String piMonitorCommandTarget;
String piMonitorSelectedCommandTarget;
String piMonitorCommandStatus = "No command sent.";
uint32_t piMonitorCommandCount = 0;
int piMonitorSetIntervalIndex = 1;
uint32_t piMonitorSetIntervalCommandCount = 0;
String piMonitorLastResponseDevice;
String piMonitorLastResponseSummary;
uint32_t piMonitorResponseCount = 0;
unsigned long piMonitorLastCommandSentMs = 0;
uint32_t piMonitorStatusPublishCount = 0;
unsigned long piMonitorLastStatusPublishMs = 0;
bool piMonitorConfigLoaded = false;
String piMonitorLastTopic;
String piMonitorLastPayload;
uint32_t piMonitorMessageCount = 0;
PiMonitorDevice piMonitorDevices[MAX_PI_MONITOR_DEVICES];
PiMonitorView piMonitorView = PiMonitorView::ProjectList;
PiMonitorProjectConfig piMonitorProjects[MAX_PI_MONITOR_PROJECTS];
PiMonitorMessage piMonitorMessages[MAX_PI_MONITOR_MESSAGES];
int selectedPiMonitorProjectIndex = 0;
int piMonitorProjectScrollOffset = 0;
int selectedPiMonitorCommandIndex = 0;
int piMonitorCommandScrollOffset = 0;
int piMonitorMessageWriteIndex = 0;
uint32_t piMonitorStoredMessageCount = 0;
SdManagerEntry sdManagerEntries[SD_MANAGER_MAX_ENTRIES];
SdManagerConfigLine sdManagerConfigLines[SD_MANAGER_CONFIG_MAX_LINES];
SdManagerView sdManagerView = SdManagerView::FolderList;
int selectedSdManagerFolderIndex = 0;
int sdManagerEntryCount = 0;
int selectedSdManagerEntryIndex = 0;
int sdManagerEntryScrollOffset = 0;
int selectedSdManagerConfigIndex = 0;
int sdManagerConfigScrollOffset = 0;
int sdManagerTextScrollOffset = 0;
int sdManagerConfigLineCount = 0;
uint64_t sdManagerCardSizeBytes = 0;
uint64_t sdManagerCardUsedBytes = 0;
int sdManagerKnownFolderCount = 0;
VoiceMemoFile voiceMemos[MAX_VOICE_MEMOS];
int voiceMemoCount = 0;
int selectedVoiceMemoIndex = 0;
int voiceMemoScrollOffset = 0;
bool voiceSdInitialized = false;
bool voiceSdAvailable = false;
bool voiceMemoRecording = false;
bool voiceMemoPlaying = false;
bool voiceMemoChunkPending = false;
bool envSensorInitialized = false;
bool envSht30Ready = false;
bool envQmp6988Ready = false;
bool envHasTempHumidity = false;
bool envHasPressure = false;
bool envPressureInvalid = false;
bool i2cHubDetected = false;
bool oledInitialized = false;
bool oledOnline = false;
bool rtcInitialized = false;
bool rtcOnline = false;
bool rtcEepromDetected = false;
bool rtcTimeValid = false;
bool rtcOscillatorStopped = false;
bool rtcTemperatureValid = false;
bool loraDiagInitialized = false;
bool loraIoExpanderDetected = false;
bool loraRfSwitchEnabled = false;
bool loraRadioReady = false;
bool loraListening = false;
bool loraGnssStarted = false;
bool loraGnssLocationValid = false;
bool loraGnssSatellitesValid = false;
bool loraGnssHdopValid = false;
bool loraGnssTimeValid = false;
bool loraGnssDateValid = false;
bool loraGnssSpeedValid = false;
bool loraGnssAltitudeValid = false;
bool gnssDashboardInitialized = false;
bool gnssSkyViewInitialized = false;
bool returnHomeInitialized = false;
bool returnHomeWaypointValid = false;
bool returnHomeNavigationValid = false;
bool envLogging = false;
bool breadcrumbLoggerInitialized = false;
bool breadcrumbLogging = false;
bool loraPacketMonitorInitialized = false;
bool loraPacketMonitorIoExpanderDetected = false;
bool loraPacketMonitorRfSwitchEnabled = false;
bool loraPacketMonitorRadioReady = false;
bool loraPacketMonitorListening = false;
bool loraPacketMonitorHasInstantRssi = false;
bool sdManagerSdAvailable = false;
bool sdManagerConfigEditingValue = false;
File voiceMemoFile;
File envLogFile;
File breadcrumbLogFile;
String voiceMemoStatus;
String activeVoiceMemoName;
String activeVoiceMemoPath;
String voiceMemoMicStatus;
String pendingVoiceMemoDeleteName;
String pendingVoiceMemoDeletePath;
String voiceMemoDeleteResultMessage;
String envStatus = "Not initialized.";
String i2cHubStatus = "Direct Grove";
String oledStatus = "Not initialized.";
String oledStatusLine;
String oledScanSummary = "Not scanned.";
String rtcStatus = "Not initialized.";
String loraStatus = "Not initialized.";
String loraRadioStatus = "Not initialized.";
String loraGnssStatus = "Not started.";
String returnHomeStatus = "Not started.";
String breadcrumbLogStatus = "Not started.";
String breadcrumbLogFileName;
String breadcrumbLogFilePath;
String loraPacketMonitorStatus = "Not initialized.";
String loraPacketMonitorLastPayload;
String sdManagerStatus = "Select folder.";
String sdManagerCurrentFolder;
String sdManagerSelectedPath;
String sdManagerSelectedName;
String sdManagerTextBuffer;
String sdManagerEditInput;
String sdManagerPendingName;
String sdManagerPendingPath;
String sdManagerResultMessage;
String sdManagerCardType = "none";
String loraLastPacket;
String loraLastNmeaLine;
String envLogStatus;
String envLogFileName;
String envLogFilePath;
String envLogNameInput;
uint32_t voiceMemoRecordedBytes = 0;
uint32_t voiceMemoSilentChunkCount = 0;
uint32_t envLogSampleCount = 0;
uint32_t oledDrawCount = 0;
unsigned long voiceMemoRecordingStartedMs = 0;
unsigned long lastVoiceMemoRenderMs = 0;
unsigned long voiceMemoChunkStartedMs = 0;
int16_t voiceRecordBuffer[VOICE_RECORD_CHUNK_SAMPLES];
int16_t voiceMemoLastPeak = 0;
int lastBatteryVoltageMv = 0;
int lastBatteryLevel = -1;
int lastVbusVoltageMv = -1;
int lastBatteryCurrentMa = 0;
int i2cHubActiveChannel = -1;
int loraRadioState = 0;
int loraPacketMonitorRadioState = 0;
int sharedSpiOwner = SHARED_SPI_OWNER_NONE;
int selectedGnssSkySatelliteIndex = -1;
uint8_t oledActiveAddress = 0;
uint32_t oledActiveBusFrequency = 0;
uint8_t rtcMonth = 0;
uint8_t rtcDay = 0;
uint8_t rtcHour = 0;
uint8_t rtcMinute = 0;
uint8_t rtcSecond = 0;
uint8_t rtcDayOfWeek = 0;
m5::Power_Class::is_charging_t lastChargingStatus = m5::Power_Class::charge_unknown;
GnssSkySatellite gnssSkySatellites[GNSS_SKY_MAX_SATELLITES];
float envTemperatureC = 0.0f;
float envHumidityPercent = 0.0f;
float envPressureHpa = 0.0f;
float rtcTemperatureC = 0.0f;
float loraLastRssi = 0.0f;
float loraLastSnr = 0.0f;
float loraPacketMonitorLastRssi = 0.0f;
float loraPacketMonitorLastSnr = 0.0f;
float loraPacketMonitorInstantRssi = 0.0f;
double loraGnssLatitude = 0.0;
double loraGnssLongitude = 0.0;
double returnHomeLatitude = 0.0;
double returnHomeLongitude = 0.0;
float loraGnssHdop = 0.0f;
float loraGnssSpeedKmph = 0.0f;
float loraGnssAltitudeMeters = 0.0f;
float returnHomeDistanceMeters = 0.0f;
float returnHomeBearingDeg = 0.0f;
uint32_t loraPacketCount = 0;
uint32_t loraCrcErrorCount = 0;
uint32_t loraReceiveErrorCount = 0;
uint32_t loraGnssByteCount = 0;
uint32_t loraGnssLineCount = 0;
uint32_t loraGnssCharsParsed = 0;
uint32_t loraGnssPassedChecksum = 0;
uint32_t loraGnssFailedChecksum = 0;
uint32_t loraGnssFixAgeMs = 0;
uint32_t loraGnssSatellites = 0;
uint32_t breadcrumbLogSampleCount = 0;
uint32_t breadcrumbLogMissedFixCount = 0;
uint32_t loraPacketMonitorPacketCount = 0;
uint32_t loraPacketMonitorCrcErrorCount = 0;
uint32_t loraPacketMonitorReceiveErrorCount = 0;
uint32_t rtcReadAttemptCount = 0;
uint32_t gnssSkySatelliteCount = 0;
uint32_t gnssSkySatellitesInView = 0;
uint32_t gnssSkyGsvSentenceCount = 0;
uint16_t loraGnssYear = 0;
uint16_t loraPacketMonitorLastPacketLength = 0;
uint16_t rtcYear = 0;
uint8_t loraGnssMonth = 0;
uint8_t loraGnssDay = 0;
uint8_t loraGnssHour = 0;
uint8_t loraGnssMinute = 0;
uint8_t loraGnssSecond = 0;
float smoothedLevelX = 0.0f;
float smoothedLevelY = 0.0f;
bool levelSmoothingInitialized = false;
